import type { Metadata } from "next";

import NavBar from "../components/shared/NavBar";
import Footer from "../components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="mx-auto container">
        <NavBar />
        {children}
        <Footer />
      </div>
    </>
  );
}
